name: Jobs
author: Wax_Dev
version: 1.0.0-beta
api: 3.0.0
main: Wax\XXWAXX\main
website: https://github.com/WAXdev974/Jobs-MCPE.git
    
commands:
    metier:
    description: plugin de metier